---
- name: Install & Secure Mysql 8 on Ubuntu
  hosts: dbserver
  become: yes

#  vars_files:
#    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installing Mysql
      package:
         name: "{{item}}"
         state: present
         update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      notify:
        - start and enable mysql service
        - Set root user password
        - Create admin user with remote access
        - Execute MySQL secure installation

    - name: Create new database
      community.mysql.mysql_db:
        name:
          - test
        state: present
      notify:
        - Restore database
      
# --------------------------------------- HANDLERS -------------------------------------------

  handlers:        
    - name: start and enable mysql service
      service:
         name: mysql
         state: started
         enabled: yes

    - name: Set root user password
      mysql_user:
        name: root
        password: "D0m@In@123"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host: localhost
        login_user: root
        login_password: ''
        state: present
   
    - name: Restore database
      community.mysql.mysql_db:
        name: test
        state: import
        target: /var/www/html/Employee-management/test1.sql
    
    - name: Execute MySQL secure installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter password for user root:': "D0m@In@123"
          'Press y\|Y for Yes, any other key for No': 'Y'
          'Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG': "0"
          'Change the password for root \? \(\(Press y\|Y for Yes, any other key for No\)': 'n'
          'Remove anonymous users\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Disallow root login remotely\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Remove test database and access to it\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Reload privilege tables now\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
      environment:
        MYSQL_PWD: "D0m@In@123"

    - name: Restart mysql
      service:
        name: mysql
        state: restarted